### ISSUE TITLE
缺少预处理数据的代码

### ISSUE THREAD

**Issue by TimeTrapzz** [haon-chen/ConvAug#1]
您好，您的代码与其他工作对数据的处理方法似乎不太一样，但是仓库里没看到相应的预处理代码，可否分享一下？十分感谢！

**Comment by haon-chen** [comment]
您好，
我们工作使用的数据格式与以往的工作并无区别（如COTED，LeCore等）。如有需要，您可以找以往工作的作者联系索要处理好的数据，或者他们的预处理代码自己处理，谢谢。数据使用方法请参考data_augmentation和sample_filter。
谢谢关注

**Comment by ZepengDu** [comment]
> 您好，您的代码与其他工作对数据的处理方法似乎不太一样，但是仓库里没看到相应的预处理代码，可否分享一下？十分感谢！

您好，请问您处理好数据了吗？
